# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sameto' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for sameto
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'sametoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
